### ISSUE TITLE
Clarify cachix write auth token support in setup guide

### ISSUE THREAD

**Issue by roberth** [hercules-ci/docs.hercules-ci.com#119]
https://github.com/hercules-ci/hercules-ci-agent/issues/347

**Comment by Kranzes** [comment]
Should this be closed now?

**Comment by roberth** [comment]
Thanks for reminding me! Yes.
Closed via #120

**Comment by quinn-dougherty** [comment]
this isn't clear at all-- i've been deep in docs and I don't see anywhere for my top level cachix account tokens https://app.cachix.org/personal-auth-tokens
