### ISSUE TITLE
Styling: linking anchors has wrong offset

### ISSUE THREAD

**Issue by domenkozar** [hercules-ci/docs.hercules-ci.com#13]
Example: https://docs.hercules-ci.com/#roadmap

Most probably needs to give more margin to pusher.

**Comment by roberth** [comment]
What is linking herfs?

Lots of things are broken about the CSS there. We'll need something that works for
 - semantic ui html
 - asciidoc html
 - docbook html

We're using some mix of the CSS that comes with these. If we want to get it right, we'll have to pick a 'standard' set of CSS rules (I'm guessing that will be semantic's CSS) and we'll have to adapt the other systems' stylesheets to work in the same way - same units, same proportions for similar things. Also we need to decide on https://github.com/hercules-ci/monorepo/issues/471.

Adjusting things here and there every now and then seems like a huge time sink with a low probability of achieving the intended result.
/rant

**Comment by domenkozar** [comment]
On the other hand, we need users to be able to view documentation - which mostly works, but the wrong margin gives bad UX, which shouldn't be hard to fix.

**Comment by roberth** [comment]
I'm certainly not opposed to quick fixes for things that are really annoying. We can certainly do one or two easy tweaks in the meantime.
