### ISSUE TITLE
nix-darwin nix install command does nothing

### ISSUE THREAD

**Issue by jezen** [hercules-ci/docs.hercules-ci.com#130]
Currently on [this page][0] the user is instructed to first run this command:

```sh
sh <(curl https://nixos.org/nix/install) --daemon
```

This does nothing, because a request to the specified URL returns a 301 permanent redirect.

I think this command should either be updated to:

```sh
sh <(curl https://releases.nixos.org/nix/nix-2.8.0/install) --daemon
```

…_or_ perhaps cURL should be configured to follow that redirect, like this:

```sh
sh <(curl --location https://nixos.org/nix/install) --daemon
```

[0]: https://docs.hercules-ci.com/hercules-ci/getting-started/deploy/nix-darwin/

**Comment by roberth** [comment]
Fixed in https://github.com/hercules-ci/docs.hercules-ci.com/commit/aac145d4df3c4edb3355de6106213f6d8ea595fa

I'm all for long options, but `--location` makes so little sense that I went with the short and common `-L` that's also on nixos.org.

Thanks for reporting!
